{% set name = "wsgidav" %}
{% set version = "4.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f0ad71bea72def3018b6ba52da3bcb83f61e0873c27225344582805d6e52b9e

build:
  entry_points:
    - wsgidav = wsgidav.server.server_cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - defusedxml
    - jinja2
    - json5
    - pyyaml

test:
  imports:
    - wsgidav
  commands:
    - pip check
    - wsgidav --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mar10/wsgidav
  summary: Generic and extendable WebDAV server based on WSGI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timj
